apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dreamvo
  name: dreamvo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: dreamvo
  template:
    metadata:
      labels:
        app: dreamvo
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - image: dreamvo/website@sha256:c4e9eb0753d0161b5ca49b4a50b85ae8cc53e56f29ad0e2106ab270549101adb
          name: dreamvo
          imagePullPolicy: Always
          args:
            - start
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 3
