apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dreamvo
  name: dreamvo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: dreamvo
  template:
    metadata:
      labels:
        app: dreamvo
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - image: dreamvo/website@sha256:571c9852d9cc4246724dc8f246d1991579bf68980e8356e20062ad2115eb8cc5
          name: dreamvo
          imagePullPolicy: Always
          args:
            - start
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 3
